services:
  api:
    build: ./api
    container_name: baul-api
    env_file: ./api/.env
    ports:
      - "5000:5000"
    restart: unless-stopped

  web:
    build: ./web
    container_name: baul-web
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped
