"""change photo_url to photos json

Revision ID: 4fc0e4df1a7e
Revises: 816987aeffce
Create Date: 2026-03-06 01:56:11.746142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc0e4df1a7e'
down_revision = '816987aeffce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pieces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photos', sa.JSON(), nullable=False))
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pieces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('photos')

    # ### end Alembic commands ###
